server:
  port: 7003

spring:
  application:
    name: zuul-gateway

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址。
      #defaultZone: http://eureka-server01:7001/eureka/,http://eureka-server02:7002/eureka/
      defaultZone: http://eureka-server01:7001/eureka/

zuul:
  routes:
    app:
      # 满足path的请求，路由到url地址或者serviceId
      path: /api/v1/apps/**
      url: localhost:7999/v1/apps
      serviceId: eureka-client